### ISSUE TITLE
Connect React Flash Cards to an Express/MongoDB Backend

### ISSUE THREAD

**Issue by jjnotjayjay** [jjnotjayjay/react-flash-cards#21]
# Tasks
- [x] Install MongoDb and write script to seed the database with initial flashcards.
- [x] Install Express and configure it to serve the static index.html, main.js, and styles.css files.
- [x] Bug: no cards message displays without a background fill.
- [x] Bug: practice-cards view crashes when there are no cards.
- [x] Configure the Express app instance to utilize a router in a separate file.
- [x] Configure router to handle GET requests to return all existing cards.
- [x] Configure router to handle POST requests to create new cards.
- [x] Configure router to handle PUT requests to update existing cards.
- [x] _Updated seed cards to include a topic field._
- [x] Configure router to handle DELETE requests to delete existing cards.
- [x] _Replace references to incrementing integer Ids with UUIDs._
- [x] React App should issue GET request to load initial cards from MongoDB instead of localstorage.
- [x] Remove unnecessary writing to localstorage upon App component unload.
- [x] Configure React App to issue POST requests to express to create new cards and re-render state.
- [x] Configure React App to issue PUT requests to express to update existing cards and re-render state.
- [x] Configure React App to issue DELETE requests to express to delete existing cards and re-render state.
- [x] Ensure Actions in React App are reflected in MongoDB.
- [x] Deploy React App to Heroku.
